//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblService()
        {
            this.tblAppointmentServices = new HashSet<tblAppointmentService>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public float Price { get; set; }
        public float FixPrice { get; set; }
        public float Discount { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdatedDate { get; set; }
        public int DealerId { get; set; }
        public string CostType { get; set; }
        public string SalesPart { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<float> PricePerUnit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAppointmentService> tblAppointmentServices { get; set; }
        public virtual tblDealer tblDealer { get; set; }
    }
}
