//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDealersMechanic
    {
        public int Id { get; set; }
        public int DealerId { get; set; }
        public int MechanicId { get; set; }
    
        public virtual tblDealer tblDealer { get; set; }
        public virtual tblMechanic tblMechanic { get; set; }
    }
}
