//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVehicle
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string Brand { get; set; }
        public string LicencePlate { get; set; }
        public string Model { get; set; }
        public Nullable<int> MeterValue { get; set; }
        public System.DateTime RegDate { get; set; }
        public Nullable<float> Weight { get; set; }
        public string MCHCode { get; set; }
        public string Vin { get; set; }
        public string EngNo { get; set; }
        public string Colour { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public int CustomerId { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
    }
}
